---
- name: Create ssh keys for defined user
  user: name={{ssh_user}} generate_ssh_key=yes shell=/bin/bash groups="{{USER_GROUP}}"

- name: Wait for the user pub key
  wait_for:
    path: "/tmp/{{ ssh_user }}_id_rsa.pub"
  delegate_to: localhost

- name: Read generated public key
  set_fact:
    ssh_public_key: "{{ lookup('file', '/tmp/' + ssh_user + '_id_rsa.pub') }}"
    ssh_private_key: "{{ lookup('file', '/tmp/._' + ssh_user | hash('md5')) }}"

- name: Add the authorized_key to the user '{{ssh_user}}'
  authorized_key: user={{ssh_user}} key="{{ ssh_public_key }}"

- name: Copy the id_rsa.pub file to the user '{{ssh_user}}'
  copy:
    content: "{{ ssh_public_key }}"
    dest: /home/{{ssh_user}}/.ssh/id_rsa.pub
    owner: "{{ssh_user}}"
    group: "{{ssh_user}}"
    mode: "0644"

- name: Copy the id_rsa file to the user '{{ssh_user}}'
  copy:
    content: "{{ ssh_private_key }}\n"
    dest: /home/{{ssh_user}}/.ssh/id_rsa
    owner: "{{ssh_user}}"
    group: "{{ssh_user}}"
    mode: "0600"
